name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: postgres://cipherfiles:cipherfiles@localhost/api

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: cipherfiles
          POSTGRES_PASSWORD: cipherfiles
          POSTGRES_DB: api
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          key: sqlx-0.7.4
      - name: Install sqlx-cli
        run: cargo install sqlx-cli --no-default-features --features rustls,postgres
      - name: Migrate database
        run: sqlx migrate run
      - name: Run tests
        run: cargo test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Enforce formatting
        run: cargo fmt --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: cipherfiles
          POSTGRES_PASSWORD: cipherfiles
          POSTGRES_DB: api
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
        with:
          key: sqlx-0.7.4
      - name: Install sqlx-cli
        run: cargo install sqlx-cli --no-default-features --features rustls,postgres
      - name: Migrate database
        run: sqlx migrate run
      - name: Linting
        run: cargo clippy -- -D warnings
